package peerport.backend.service;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import peerport.backend.database.GradesRepository;
import peerport.backend.exceptions.assignmentSubmissions.AssignmentSubmissionNotFoundException;
import peerport.backend.exceptions.grades.GradeNotFoundException;
import peerport.backend.model.AssignmentSubmissionModel;
import peerport.backend.model.GradeModel;

@Service
public class GradeService {
    protected static final Logger logger = LoggerFactory.getLogger(GradeService.class);

    @Autowired
    private GradesRepository gradeRepository;

    @Autowired
    private AssignmentSubmissionService assignmentSubmissionService;

    /**
     * Retrieves all grades from the database and returns them as a list. 
     * If there are no grades in the database, an empty list is returned.
     * @return A list of all GradeModel objects in the database, or an empty list if there are no grades.
     */
    public List<GradeModel> getAllGrades() {
        logger.debug("Retrieving all grades from the database");
        return gradeRepository.findAll();
    }
    
    /**
     * Retrieves a grade by its ID. If the grade is not found, a GradeNotFoundException is thrown.
     * @param gradeId - The ID of the grade to retrieve
     * @return The GradeModel with the given ID
     * @throws GradeNotFoundException if no grade with the given ID is found in the database
    */
    public GradeModel getGradeById(String gradeId) throws GradeNotFoundException {
        logger.debug("Attempting to retrieve grade with ID: {}", gradeId);
        
        // Try to get the grade from the database
        Optional<GradeModel> grade = gradeRepository.findById(gradeId);

        if (!grade.isPresent()) {
            logger.warn("Failed to retrieve grade with ID: \"{}\", Reason: not found", gradeId);
            throw new GradeNotFoundException(gradeId);
        }

        logger.debug("Successfully retrieved grade with ID: {}", gradeId);
        return grade.get();
    }

    /**
     * Creates a new grade and links it to the assignment submission with 
     * the given ID. The grade is saved to the database and returned.
     * @param grade - The GradeModel containing the gradeObtained, maxGrade, and feedback values for the new grade. The gradeId field is ignored and generated by the database.
     * @param submissionId - The ID of the AssignmentSubmissionModel to link the new grade to. The grade will be set on the submission and the submission will be saved to the database.
     * @return The created GradeModel after saving it to the database, including the generated gradeId field. The returned GradeModel is linked to the submission with the given ID.
     * @throws AssignmentSubmissionNotFoundException if no assignment submission with the given ID is found
     */
    public GradeModel createGrade(GradeModel grade, String submissionId) {
        logger.debug("Attempting to create grade for submission with ID: {}", submissionId);
        
        // Get the submission to link the grade to
        AssignmentSubmissionModel submission = this.assignmentSubmissionService.getSubmissionById(submissionId);
        logger.trace("Successfully retrieved submission with ID: {} to link the new grade to", submissionId);

        // Link the grade to the submission
        submission.setGrade(grade);

        // Save the grade
        GradeModel savedGrade = gradeRepository.save(grade);
        
        // Return the saved grade
        logger.debug("Successfully created grade with ID: {}", savedGrade.getGradeId());
        return savedGrade;
    }

    /**
     * Updates an existing grade with new values. Only the gradeObtained, maxGrade, and feedback fields can be updated.
     * @param gradeId - The ID of the grade to update
     * @param updatedGrade - A GradeModel containing the updated values for the gradeObtained, maxGrade, and feedback fields. The gradeId field is ignored.
     * @return The updated GradeModel after saving it to the database
     * @throws GradeNotFoundException if no grade with the given ID is found in the database
     */
    public GradeModel updateGrade(String gradeId, GradeModel updatedGrade) throws GradeNotFoundException {
        logger.debug("Attempting to update grade with ID: {}", gradeId);
        
        // Get the existing grade from the database
        GradeModel existingGrade = getGradeById(gradeId);

        // Update the grade fields
        existingGrade.setGradeObtained(updatedGrade.getGradeObtained());
        existingGrade.setMaxGrade(updatedGrade.getMaxGrade());
        existingGrade.setFeedback(updatedGrade.getFeedback());

        // Save the updated grade back to the database
        GradeModel savedGrade = gradeRepository.save(existingGrade);
        
        // Return the updated grade
        logger.debug("Successfully updated grade with ID: {} from score of {}/{} to {}/{}", 
                    savedGrade.getGradeId(),
                    existingGrade.getGradeObtained(), 
                    existingGrade.getMaxGrade(),
                    savedGrade.getGradeObtained(), 
                    savedGrade.getMaxGrade()
        );
        return savedGrade;
    }

    /**
     * Deletes a grade by its ID
     * @param gradeId - The ID of the grade to delete
     * @return true if the grade was successfully deleted, false if the grade was not found
     * @throws GradeNotFoundException if no grade with the given ID is found in the database
     */
    public boolean deleteGrade(String gradeId) throws GradeNotFoundException {
        logger.debug("Attempting to delete grade with ID: {}", gradeId);

        // Get the grade to ensure it exists (will throw if not found)
        GradeModel gradeToDelete = getGradeById(gradeId);

        // Delete the grade from the database
        gradeRepository.delete(gradeToDelete);

        // Return a success response
        logger.debug("Successfully deleted grade with ID: {}", gradeId);
        return true;
    }
}
